function plays_length = computePlayLength(plays)
% The function computes the length of a given play. For computing the
% length, only the pass and the free kick events are counted as these are
% events generated by the offensive team on purpose. Duels, others on the
% ball, and siilar events are not planned. While shots are planned, we
% decided to exclude them for simplicity and to have a similar metric
% between plays with and without a shot.

    plays_length = zeros(numel(plays), 1);

    for i = 1:numel(plays)
        current_play    = plays{i};
        plays_length(i) = getPlayLength(current_play);
    end
end

function play_length = getPlayLength(play)
    valid_events = {'Pass', 'Free Kick'};
    ev_names     = {play.eventName};
    play_length  = sum(contains(ev_names, valid_events));
end

