function fifa_attr_data = load_fifa_attribute_data()
%IMPORTFILE Import data from a text file
%  FIFACOMPLETEDATASET = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  FIFACOMPLETEDATASET = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  fifaCompleteDataset = importfile("C:\Users\omar_\MATLAB\Projects\football_event_analysis\data\fifa_CompleteDataset.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 24-Sep-2022 10:16:45

filename = 'fifa_CompleteDataset.csv';

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 39);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Overall", "Potential", "Value", "Wage", "Acceleration", "Aggression", "Agility", "Balance", "BallControl", "Composure", "Crossing", "Curve", "Dribbling", "Finishing", "FreeKickAccuracy", "GKDiving", "GKHandling", "GKKicking", "GKPositioning", "GKReflexes", "HeadingAccuracy", "Interceptions", "Jumping", "LongPassing", "LongShots", "Marking", "Penalties", "Positioning", "Reactions", "ShortPassing", "ShotPower", "SlidingTackle", "SprintSpeed", "Stamina", "StandingTackle", "Strength", "Vision", "Volleys", "ID"];
opts.VariableTypes = ["double", "double", "string", "string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% % Specify variable properties
% opts = setvaropts(opts, ["Value", "Wage"], "TrimNonNumeric", true);
% opts = setvaropts(opts, ["Value", "Wage"], "ThousandsSeparator", ",");

% Import the data
fifa_attr_data = readtable(filename, opts);

end