function tfplayervaluations = load_tf_market_value_data()
%LOAD_TF_MARKET_VALUE_DATA Import data from a text file
%  TFPLAYERVALUATIONS = LOAD_TF_MARKET_VALUE_DATA(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  Example:
%  tfplayervaluations = load_tf_market_value_data();
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 22-Sep-2022 21:04:12

% filename = 'tf_player_valuations.csv';
filename = 'tf_player_valuations_short.csv';

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["player_id", "date", "market_value"];
opts.VariableTypes = ["double", "datetime", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "date", "InputFormat", "dd/MM/yyyy");

% Import the data
tfplayervaluations = readtable(filename, opts);

end