function tfplayers = load_tf_player_data()
%LOADTFPLAYERDATA Import player data from transfermarkt
%  TFPLAYERS = LOADTFPLAYERDATA() reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  Example:
%  tfplayers = load_tf_player_data();
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 22-Sep-2022 19:14:37

filename = 'tf_players.csv';

%% Input handling

dataLines = [2, Inf];

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 21);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["player_id", "last_season", "current_club_id", "name", "pretty_name", "country_of_birth", "country_of_citizenship", "date_of_birth", "position", "sub_position", "foot", "height_in_cm", "market_value_in_gbp", "highest_market_value_in_gbp", "agent_name", "image_url", "url", "club_id", "domestic_competition_id", "club_name", "club_pretty_name"];
opts.VariableTypes = ["double", "double", "double", "string", "string", "categorical", "categorical", "datetime", "categorical", "categorical", "categorical", "double", "double", "double", "string", "string", "string", "double", "categorical", "categorical", "categorical"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["name", "pretty_name", "agent_name", "image_url", "url"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["name", "pretty_name", "country_of_birth", "country_of_citizenship", "position", "sub_position", "foot", "agent_name", "image_url", "url", "domestic_competition_id", "club_name", "club_pretty_name"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "date_of_birth", "InputFormat", "yyyy-MM-dd");

% Import the data
tfplayers = readtable(filename, opts);

end