function [grammar_rules] = importGrammarRules(filename, dataLines)
    %IMPORTFILE Import data from a text file
    %  CANNONICALCORNERALLRULES = IMPORTFILE(FILENAME) reads data from text
    %  file FILENAME for the default selection.  Returns the data as a table.
    %
    %  CANNONICALCORNERALLRULES = IMPORTFILE(FILE, DATALINES) reads data for
    %  the specified row interval(s) of text file FILENAME. Specify
    %  DATALINES as a positive scalar integer or a N-by-2 array of positive
    %  scalar integers for dis-contiguous row intervals.
    %
    %  Example:
    %  cannonicalcornerAllrules = importfile("C:\Users\omar_\MATLAB\Projects\football_event_analysis\grammar_rules\Corners\cannonical_corner_All_rules.csv", [2, Inf]);
    %
    %  See also READTABLE.
    %
    % Auto-generated by MATLAB on 27-Jun-2022 23:33:59

    %% Input handling

    % If dataLines is not specified, define defaults
    if nargin < 2
        dataLines = [2, Inf];
    end

    %% Set up the Import Options and import the data
    opts = delimitedTextImportOptions("NumVariables", 9);

    % Specify range and delimiter
    opts.DataLines = dataLines;
    opts.Delimiter = ",";

    % Specify column names and types
    opts.VariableNames = ["Rule", "Raw", "Expand", "RRF", "DF", "RPF", "PF", "PF_perc", "RPFdivPF"];
    opts.VariableTypes = ["double", "string", "string", "double", "double", "double", "double", "double", "double"];

    % Specify file level properties
    opts.ExtraColumnsRule = "ignore";
    opts.EmptyLineRule = "read";

    % Specify variable properties
    opts = setvaropts(opts, ["Raw", "Expand"], "WhitespaceRule", "preserve");
    opts = setvaropts(opts, ["Raw", "Expand"], "EmptyFieldRule", "auto");

    % Import the data
    grammar_rules = readtable(filename, opts);

    
    %% Clear temporary variables
    clear opts
end